id: P004408
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1CZ1115
  title: འཕགས་པ་གླང་རུ་ལུང་བསྟན
  author: ''
  volumes:
    8d05d756ef244aecaad34e0807e08ed4:
      image_group_id: I1CZ1392
      title: ''
      volume_number: 1
      total_pages: 44
      base_file: v001.txt
